### ISSUE TITLE
EcoSense Images

### ISSUE THREAD

**Issue by ollers** [ollers/ecosense#1]
![image](https://cloud.githubusercontent.com/assets/9365632/5804136/7783c0c2-9ffb-11e4-9d69-73d7c0ced202.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804139/7f4e8184-9ffb-11e4-8055-1c6d919c63bd.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804141/84fb29c0-9ffb-11e4-944a-916cd6a85fb9.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804147/8cb0d818-9ffb-11e4-8f87-a6c2d954fe08.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804148/9498b6f4-9ffb-11e4-976e-d9a177c30d9e.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804151/9c7714d8-9ffb-11e4-87bc-7804e430d0a9.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804153/a318b54e-9ffb-11e4-9663-d72805f0f08c.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804157/a874aae8-9ffb-11e4-8f4c-a8a47e7210e9.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804159/acfa51ee-9ffb-11e4-8248-1e7856ac2e86.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804163/b55148f2-9ffb-11e4-96d8-8f369e4a2954.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804164/c133e314-9ffb-11e4-9c62-8c4a7b188d5f.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804167/c61dc6a6-9ffb-11e4-9de0-6f735d491a0c.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804169/ca68837c-9ffb-11e4-9afd-199a59e20543.png)

![image](https://cloud.githubusercontent.com/assets/9365632/5804174/d02c1170-9ffb-11e4-9f1f-91a019fd18d2.png)

**Comment by Dr-Uid** [comment]
![ecologo](https://cloud.githubusercontent.com/assets/10538221/5828438/ff5fc918-a0fb-11e4-9981-29fa6959e008.png)

**Comment by Dr-Uid** [comment]
![ecoenseorange](https://cloud.githubusercontent.com/assets/10538221/5837760/c74b8598-a179-11e4-9417-cb6c1c37e2f7.png)

**Comment by ollers** [comment]
These images were saved as a solution to referencing images on Git Hub. This is no longer needed as site will not be demoed on Git Hub plus managed to upload site assets.
